// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"goelster/app"
	"goelster/controller"
	"goelster/middleware"
	"goelster/repository"
	"goelster/service"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	akunRepositoryImpl := repository.NewAkunRepositoryImpl()
	db := app.GetConnection()
	validate := validator.New()
	akunServiceImpl := service.NewAkunService(akunRepositoryImpl, db, validate)
	akunControllerImpl := controller.NewAkunController(akunServiceImpl)
	pengajuanBimbinganRepositoryImpl := repository.NewPengajuanBimbinganRepository()
	pengajuanBimbinganServiceImpl := service.NewPegajuanBimbinganService(pengajuanBimbinganRepositoryImpl, db, validate)
	pengajuanBimbinganControllerImpl := controller.NewPengajuanBimbinganController(pengajuanBimbinganServiceImpl)
	pengajuanSemproRepositoryImpl := repository.NewPengajuanSemproRepository()
	pengajuanSemproServiceImpl := service.NewPengajuanSemproService(pengajuanSemproRepositoryImpl, db, validate)
	pengajuanSemproControllerImpl := controller.NewPengajuanSemproController(pengajuanSemproServiceImpl)
	dospemRepositoryImpl := repository.NewDospemRepository()
	dospemServiceImpl := service.NewDospemService(dospemRepositoryImpl, db, validate)
	dospemControllerImpl := controller.NewDospemController(dospemServiceImpl)
	pengajuanSeminarHasilRepositoryImpl := repository.NewPengajuanSeminarHasilRepository()
	pengajuanSeminarHasilServiceImpl := service.NewPengajuanSeminarHasilService(pengajuanSeminarHasilRepositoryImpl, db, validate)
	pengajuanSeminarHasilControllerImpl := controller.NewPengajuanSeminarHasilController(pengajuanSeminarHasilServiceImpl)
	pengajuanUjianTaRepositoryImpl := repository.NewPengajuanUjianTaRepository()
	pengajuanUjianTaServiceImpl := service.NewPengajuanUjianTaService(pengajuanUjianTaRepositoryImpl, db, validate)
	pengajuanUjianTaControllerImpl := controller.NewPengajuanUjianTaController(pengajuanUjianTaServiceImpl)
	router := app.NewRouter(akunControllerImpl, pengajuanBimbinganControllerImpl, pengajuanSemproControllerImpl, dospemControllerImpl, pengajuanSeminarHasilControllerImpl, pengajuanUjianTaControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var registerSet = wire.NewSet(repository.NewAkunRepositoryImpl, wire.Bind(new(repository.AkunRepository), new(*repository.AkunRepositoryImpl)), service.NewAkunService, wire.Bind(new(service.AkunService), new(*service.AkunServiceImpl)), controller.NewAkunController, wire.Bind(new(controller.AkunController), new(*controller.AkunControllerImpl)))

var bimbinganSet = wire.NewSet(repository.NewPengajuanBimbinganRepository, wire.Bind(new(repository.PengajuanBimbinganRepository), new(*repository.PengajuanBimbinganRepositoryImpl)), service.NewPegajuanBimbinganService, wire.Bind(new(service.PengajuanBimbinganService), new(*service.PengajuanBimbinganServiceImpl)), controller.NewPengajuanBimbinganController, wire.Bind(new(controller.PengajuanBimbinganController), new(*controller.PengajuanBimbinganControllerImpl)))

var semproSet = wire.NewSet(repository.NewPengajuanSemproRepository, wire.Bind(new(repository.PengajuanSemproRepository), new(*repository.PengajuanSemproRepositoryImpl)), service.NewPengajuanSemproService, wire.Bind(new(service.PengajuanSemproService), new(*service.PengajuanSemproServiceImpl)), controller.NewPengajuanSemproController, wire.Bind(new(controller.PengajuanSemproController), new(*controller.PengajuanSemproControllerImpl)))

var dospemset = wire.NewSet(repository.NewDospemRepository, wire.Bind(new(repository.DospemRepository), new(*repository.DospemRepositoryImpl)), service.NewDospemService, wire.Bind(new(service.DospemService), new(*service.DospemServiceImpl)), controller.NewDospemController, wire.Bind(new(controller.DospemController), new(*controller.DospemControllerImpl)))

var seminarhasilset = wire.NewSet(repository.NewPengajuanSeminarHasilRepository, wire.Bind(new(repository.PengajuanSeminarHasilRepository), new(*repository.PengajuanSeminarHasilRepositoryImpl)), service.NewPengajuanSeminarHasilService, wire.Bind(new(service.PengajuanSeminarHasilService), new(*service.PengajuanSeminarHasilServiceImpl)), controller.NewPengajuanSeminarHasilController, wire.Bind(new(controller.PengajuanSeminarHasilController), new(*controller.PengajuanSeminarHasilControllerImpl)))

var ujiantaset = wire.NewSet(repository.NewPengajuanUjianTaRepository, wire.Bind(new(repository.PengajuanUjianTaRepository), new(*repository.PengajuanUjianTaRepositoryImpl)), service.NewPengajuanUjianTaService, wire.Bind(new(service.PengajuanUjianTaService), new(*service.PengajuanUjianTaServiceImpl)), controller.NewPengajuanUjianTaController, wire.Bind(new(controller.PengajuanUjianTaController), new(*controller.PengajuanUjianTaControllerImpl)))
